image:
  repository: 006393696278.dkr.ecr.us-east-1.amazonaws.com/eolas
  tag: "latest"
  pullPolicy: Always
service:
  publicHostName: eolas.prod.apps.k8s.riglet.io
  authUrl: http://heimdall-prod-heimdall.public.svc.cluster.local/valid?unauthCode=200
app:
  dbUrl: mongodb://mongo-staging-mongodb.default.svc.cluster.local:27017
  context: prod
  # do we need it?
  nodeEnv: production
  auth: true
