image:
  repository: builditdigital/eolas
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  hostName: eolas.prod.kube.local
  authUrl: http://heimdall-prod-heimdall.public.svc.cluster.local/valid?unauthCode=200
app:
  dbUrl: mongodb://mongo-staging-mongodb:27017
  context: prod
  # do we need it?
  nodeEnv: production
  auth: true

