{{- if .Values.service.hostName }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  annotations:
    ingress.kubernetes.io/enable-cors: "true"
    {{- if .Values.service.authUrl }}
    ingress.kubernetes.io/auth-url: {{ .Values.service.authUrl }}
    ingress.kubernetes.io/auth-response-headers: X-User
    {{- end }}
spec:
  rules:
  - host: {{ .Values.service.hostName | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
{{- end }}
